services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports: 
      - "1883:1883" #mqtt port standard , mapping host port to docker port 
    volumes: #αρχειο με τις οδηγιες για τον mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf #config volume - οδηγιες 
  
  db:
    image: timescale/timescaledb:latest-pg16 #timescaledb light για λογους απλοτητας - αποθηκευση μεσα στο dokcer
    container_name: db
    environment: #περιβαλλοντικες μεταβλητες
      POSTGRES_USER: postgres #database username 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foo #ονομα βασης που θα μπουν οι πινακες
    ports:
      - "5432:5432" #port standard 
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql #volume map για να τρεξει το αρχικο sql script που δημιουργει τον πινακα στην βαση δεδομενων
      - ./db_data:/var/lib/postgresql/data #μονιμη αποθηκευση δεδομενων

  publisher_1:
    build: 
      context: ./publisher #φακελος
      dockerfile: Dockerfile.publisher #ονομα αρχειου με οδηγιες για τους publishers
      #no ports , στελνει μονο δεδομενα 
    environment: #περιβαλλοντικες μεταβλητες για να 
      MQTT_BROKER: mosquitto #broker ειναι το container mosquitto 
      DEVICE_NAME: sensor_01 #ονομα αισθητηρα 
    depends_on:
      - mosquitto #ξεκιναει publisher μετα απο mosquitto 

  publisher_2:
    build:
      context: ./publisher #φακελος
      dockerfile: Dockerfile.publisher #ονομα αρχειου με οδηγιες για τους publishers
      #no ports , στελνει μονο δεδομενα 
    environment:
      MQTT_BROKER: mosquitto #broker ειναι το container mosquitto 
      DEVICE_NAME: sensor_02 #ονομα αισθητηρα 
    depends_on:
      - mosquitto #ξεκιναει publisher μετα απο mosquitto 

  publisher_3:
    build: 
      context: ./publisher #φακελος
      dockerfile: Dockerfile.publisher #ονομα αρχειου με οδηγιες για τους publishers
      #no ports , στελνει μονο δεδομενα 
    environment:
      MQTT_BROKER: mosquitto #broker ειναι το container mosquitto 
      DEVICE_NAME: sensor_03 #ονομα αισθητηρα 
    depends_on:
      - mosquitto #ξεκιναει publisher μετα απο mosquitto 

  subscriber: 
    build:
      context: ./subscriber #φακελος
      dockerfile: Dockerfile.subscriber #αρχειο με οδηγιες για subscriber
    environment:
      MQTT_BROKER: mosquitto
      DB_HOST: db
      DB_NAME: foo
      DB_USER: postgres
      DB_PASS: postgres
    depends_on: 
      - mosquitto
      - db #εξαρτηση και απο βαση δεδομενων - γραφει στο db

  api: 
    build:
      context: ./api # Ο φάκελος που έχει το main.py
      dockerfile: Dockerfile.api # Το αρχείο οδηγιών για το FastAPI
    ports:
      - "8000:8000" # Απαραίτητο για να ανοίγει η σελίδα στο http://localhost:8000
    depends_on: 
      - db # Εξασφαλίζει ότι το API ξεκινάει αφού έχει ξεκινήσει η βάση

  cadvisor: #για monitoring των containers και του host συστήματος
    image: gcr.io/cadvisor/cadvisor:latest 
    container_name: cadvisor
    ports:
      - "8080:8080" #port που χρησιμοποιει το cadvisor για να δειχνει τα metrics του
    volumes: #τα volumes που χρειάζεται το cadvisor για να έχει πρόσβαση σε πληροφορίες του host συστήματος και των containers
      - /:/rootfs:ro 
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  prometheus: #για συλλογή metrics απο cadvisor και node exporter
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana: #για visualization των metrics που συλλέγει το prometheus
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  node-exporter: #για συλλογή metrics του host συστήματος 
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"